### ISSUE TITLE
Links to pretrained models 

### ISSUE THREAD

**Issue by thongnt99** [Narabzad/LaQuE#1]
Dear @Narabzad, 

Thanks for a great work and very useful entity resource.
I am interested in your pretrained models, however the links you provided seem to be expired or deleted. 
Could you please update the new link? 
It would be very useful if you upload it to Huggignface as well. 

Thank you very much in advance,

**Comment by thongnt99** [comment]
I found it from: https://zenodo.org/records/8408385 
Thanks.

**Comment by Narabzad** [comment]
Hello,

Thanks for opening this issue. Sure. Soon we will update our models into hugging face.
I am glad you found them on Zenodo.
Let me know if you have any questions.
